Обсуждение проноса олимпийского факела по улицам Пскова
========================================================


```{r loading, echo=F, include=F}
Sys.setlocale('LC_TIME', 'ru_RU.UTF-8')
options(device = function(file, width = 7, height = 7, ...) {
  cairo_pdf(tempfile(), width = width, height = height, ...)
})
pdf.options(encoding='Cyrillic.enc')
library(lubridate)
library(ggplot2)
library(scales)
library(stringr)
library(pander)
library(plyr)

source('../R/read.google.spreadsheet.r')
source('../R/setkey.r')
source('../R/functions.r')

rmd.table <- function(t) {
  require(pander)
  pandoc.table(t, style = 'rmarkdown', split.tables = Inf,
             split.cells = Inf)
  }

data <- read.google.spreadsheet()
gender <- read.google.spreadsheet(3)
gender$author <- str_trim(as.character(gender$author))
# data$author <- factor(str_trim(as.character(data$author)))
data$author <- factor(str_trim(as.character(data$author)))
data$date <- str_trim(as.character(data$date))
data$time <- str_trim(as.character(data$time))
data <- data[data$time != '' & data$author != '',]
data$timestamp <- dmy_hms(str_c(data$date, data$time, sep=' '))
data$nchcomm <- str_length(data$text)

data$authnumb  <- laply(seq_len(dim(data)[1]), function(x) {
  length(unique(data$author[seq_len(x)]))
  })

data <- join(data, gender[, c('author', 'gender')])
data$gender <- factor(data$gender, 
                      labels = c("Женщина", "Мужчина"))
```

```{r createtable, results='asis', echo=FALSE}

t <- as.data.frame(table(str_trim(as.character(data$author))))
# rmd.table(t)
```

```{r timeofcommentbar, echo=FALSE}

f <- ggplot(data, aes(timestamp)) + geom_bar()
f <- f + ylab('Количество комментариев') + xlab('') +
  ggtitle('Всплески комментариев приходятся на
23 часа 21 октября и 11 часов 22 октября')
print(f)
```

```{r timeofcommentdensity, echo=FALSE}

f <- ggplot(data, aes(timestamp)) + geom_density()
f <- f + ylab('Относительная плотность комментариев') + xlab('') +
  ggtitle('Всплески комментариев приходятся на
23 часа 21 октября и 11 часов 22 октября') +
  scale_y_continuous(breaks=NULL)
print(f)
```

```{r nchardensity, echo=FALSE}

f <- ggplot(data, aes(nchcomm)) + geom_density()
f <- f + ylab('Плотность длины комментариев') + xlab('') +
  ggtitle('Чаще всего длина комментария\nне превышает 100 символов') +
  scale_y_continuous(breaks=NULL)
print(f)
```


```{r ncharbar, echo=FALSE}

txt <- data.frame(
  x = 400,
  y = 7:8,
  value = c(mean(data$nchcomm, na.rm = T), 
    median(data$nchcomm, na.rm = T)),
  label = str_c(
    c("Среднее: ", "Медиана: "),
    c(
      round(mean(data$nchcomm, na.rm = T), 1),
      round(median(data$nchcomm, na.rm = T), 1))),
  clr = c('blue', 'red'))
  
f <- ggplot(data, aes(nchcomm)) + geom_bar(binwidth=20, color='black', 
                                           fill='white') +
  geom_vline(data = txt, aes(xintercept = value, color = clr)) +
  geom_text(data = txt, aes(x, y, label = label, color = clr), hjust = 0) +
  guides(color = F)
f <- f + ylab('Количество комментариев с данной длиной') + 
  xlab('Длина комментария, символов') +
  ggtitle('В половине случаев длина комментария\nне превышает 111 символов') 
print(f)
```

###Накопление объёма информации по времени

```{r ncharcummbytime, echo=FALSE}

f <- ggplot(data) + 
  geom_step(aes(timestamp, cumsum(nchcomm))) 
f <- f + ylab('Суммарное количество символов') + 
  xlab('') +
  ggtitle('Накопление информации в течение времени')

print(f + geom_night(f))


f <- ggplot(data) + 
  geom_step(aes(timestamp, cumsum(nchcomm)/sum(nchcomm))) 
f <- f + ylab('Доля от суммарного\nколичества символов') + 
  xlab('') +
  ggtitle('Накопление информации в течение времени') +
  scale_y_continuous(labels = percent)
print(f + geom_night(f))

```

```{r authors, echo=FALSE}
f <- ggplot(data) + 
  geom_step(aes(timestamp, authnumb)) 
f <- f + ylab('Число пользователей, принявших участие в обсуждении') + 
  xlab('') +
  ggtitle('Появление новых комментаторов в течение времени') 
print(f + geom_night(f))
```


```{r authorsinfo, echo=FALSE}
f <- ggplot(data, aes(authnumb, cumsum(nchcomm))) + 
  geom_step() + geom_point()
f <- f + xlab('Число пользователей, принявших участие в обсуждении') + 
  ylab('Суммарное количество символов') +
  ggtitle('Вклад новых пользователей в объём информации') 
print(f)
```

### Пол

```{r timeofcommentbar_gender, echo=FALSE}

f <- ggplot(data, aes(timestamp, fill = gender)) + 
  geom_bar(position = 'dodge', binwidth = 3600 * 3)
f <- f + xlab('') +
  scale_y_continuous(name = 'Количество комментариев',
                     breaks = 1:10) +
  ggtitle('Различия по времени между мужскими\nи женскими комментариями') +
  scale_fill_discrete(name = "Пол автора") +
  theme(legend.justification = c(1, 1), legend.position = c(1, 1))
print(f)
```

```{r timeofcommentdensity_gender, echo=FALSE}

f <- ggplot(data, aes(timestamp, fill = gender)) + 
  geom_density(alpha = .3)
f <- f + xlab('') +
  ggtitle('Различия по времени между мужскими\nи женскими комментариями') +
    scale_y_continuous(breaks=NULL, 
                       name = "Плотность: чем выше, тем больше комментариев") +
  scale_fill_discrete(name = "Пол автора") +
  theme(legend.justification = c(1, 1), legend.position = c(1, 1))
print(f)
```

```{r nchar_gender, echo=FALSE}

f <- ggplot(data, aes(gender, nchcomm)) + geom_boxplot()
f <- f + xlab('') +
  ggtitle('Различие длин комментариев мужчин и женщин') +
    scale_y_continuous(name = "Количество символов в комментарии") +
  xlab('')
print(f)
```